### ISSUE TITLE
Google Chrome extension does not exist

### ISSUE THREAD

**Issue by Qwerty-Space** [brkastner/SDownload#123]
Title says it all.  The extension does not exist for Google Chrome.  I right click on the icon  the taskbar and click 'Download Chrome extension' and it leads me to a page that says it does not exist.

**Comment by brkastner** [comment]
The extension was removed from the Google webstore because it facilitates the download of copyrighted material.

I am in the process of porting the extension to Firefox and will have a release out soon. If you want to download the Chrome extension in the mean time, you can find the extension file at: https://github.com/brkastner/SDownload/raw/master/SDownloader/Extensions/Chrome.crx

To install:
Open Chrome and navigate to "chrome://extensions", or go to Tools > Extensions to get to the same page. Then drag the Chrome.crx file from the folder it's saved in to on top of the extensions page and you should receive a prompt to install.

**Comment by Qwerty-Space** [comment]
Thanks.  Maybe an update for the application would be to download it from that website.
